USE [tailandia]
GO

/****** Object:  Table [dbo].[SEMEAR_P_EMAIL]    Script Date: 25/07/2023 21:30:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SEMEAR_P_EMAIL](
	[SQ_EMAIL_P] [int] NOT NULL,
	[SQ_PESSOA_FK] [int] NULL,
	[Email] [varchar](max) NULL,
 CONSTRAINT [PK_SEMEAR_EMAIL_P] PRIMARY KEY CLUSTERED 
(
	[SQ_EMAIL_P] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SEMEAR_P_EMAIL]  WITH CHECK ADD  CONSTRAINT [FK_SEMEAR_EMAIL_P_SEMEAR_PESSOA] FOREIGN KEY([SQ_PESSOA_FK])
REFERENCES [dbo].[SEMEAR_PESSOA] ([SQ_PESSOA])
GO

ALTER TABLE [dbo].[SEMEAR_P_EMAIL] CHECK CONSTRAINT [FK_SEMEAR_EMAIL_P_SEMEAR_PESSOA]
GO

