USE [tailandia]
GO

/****** Object:  Table [dbo].[SEMEAR_P_TELEFONE]    Script Date: 25/07/2023 21:31:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SEMEAR_P_TELEFONE](
	[SQ_TELEFONE] [int] NOT NULL,
	[SQ_PESSOA_FK] [int] NULL,
	[Telefone] [varchar](50) NULL,
 CONSTRAINT [PK_SEMEAR_TELEFONE_P] PRIMARY KEY CLUSTERED 
(
	[SQ_TELEFONE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SEMEAR_P_TELEFONE]  WITH CHECK ADD  CONSTRAINT [FK_SEMEAR_TELEFONE_P_SEMEAR_PESSOA] FOREIGN KEY([SQ_PESSOA_FK])
REFERENCES [dbo].[SEMEAR_PESSOA] ([SQ_PESSOA])
GO

ALTER TABLE [dbo].[SEMEAR_P_TELEFONE] CHECK CONSTRAINT [FK_SEMEAR_TELEFONE_P_SEMEAR_PESSOA]
GO

