USE [tailandia]
GO

/****** Object:  Table [dbo].[SEMEAR_T_IMAGEM]    Script Date: 25/07/2023 21:32:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SEMEAR_T_IMAGEM](
	[SQ_IMAGEM_T] [bigint] NOT NULL,
	[SQ_TRANSPORTE_FK] [bigint] NULL,
	[IMAGEM] [image] NULL,
 CONSTRAINT [PK_SEMEAR_T_IMAGEM] PRIMARY KEY CLUSTERED 
(
	[SQ_IMAGEM_T] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SEMEAR_T_IMAGEM]  WITH CHECK ADD  CONSTRAINT [FK_SEMEAR_T_IMAGEM_SEMEAR_TRANSPORTE] FOREIGN KEY([SQ_TRANSPORTE_FK])
REFERENCES [dbo].[SEMEAR_TRANSPORTE] ([SQ_TRANSPORTE])
GO

ALTER TABLE [dbo].[SEMEAR_T_IMAGEM] CHECK CONSTRAINT [FK_SEMEAR_T_IMAGEM_SEMEAR_TRANSPORTE]
GO

