USE [tailandia]
GO

/****** Object:  Table [dbo].[SEMEAR_T_TELEFONE]    Script Date: 25/07/2023 21:32:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SEMEAR_T_TELEFONE](
	[SQ_TELEFONE_T] [bigint] NOT NULL,
	[SQ_TRANSPORTE_FK] [bigint] NULL,
	[TELEFONE] [varchar](50) NULL,
 CONSTRAINT [PK_SEMEAR_T_TELEFONE] PRIMARY KEY CLUSTERED 
(
	[SQ_TELEFONE_T] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SEMEAR_T_TELEFONE]  WITH CHECK ADD  CONSTRAINT [FK_SEMEAR_T_TELEFONE_SEMEAR_T_TELEFONE] FOREIGN KEY([SQ_TRANSPORTE_FK])
REFERENCES [dbo].[SEMEAR_TRANSPORTE] ([SQ_TRANSPORTE])
GO

ALTER TABLE [dbo].[SEMEAR_T_TELEFONE] CHECK CONSTRAINT [FK_SEMEAR_T_TELEFONE_SEMEAR_T_TELEFONE]
GO

