USE [tailandia]
GO

/****** Object:  Table [dbo].[SEMEAR_ASSOCIATIVA_VPR]    Script Date: 25/07/2023 21:00:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SEMEAR_ASSOCIATIVA_VPR](
	[SQ_HPR_PK] [bigint] NOT NULL,
	[SQ_VIAGEM_FK] [int] NULL,
	[SQ_RESERVA_FK] [bigint] NULL,
	[SQ_CLIENTE_FK] [int] NULL,
	[DT_INCLUSAO] [datetime] NULL,
	[DT_EXCLUSAO] [datetime] NULL,
	[DT_EDICAO] [datetime] NULL,
 CONSTRAINT [PK_Tabela1] PRIMARY KEY CLUSTERED 
(
	[SQ_HPR_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SEMEAR_ASSOCIATIVA_VPR]  WITH CHECK ADD  CONSTRAINT [FK_SEMEAR_ASSOCIATIVA_HPR_SEMEAR_PESSOA] FOREIGN KEY([SQ_CLIENTE_FK])
REFERENCES [dbo].[SEMEAR_PESSOA] ([SQ_PESSOA])
GO

ALTER TABLE [dbo].[SEMEAR_ASSOCIATIVA_VPR] CHECK CONSTRAINT [FK_SEMEAR_ASSOCIATIVA_HPR_SEMEAR_PESSOA]
GO

ALTER TABLE [dbo].[SEMEAR_ASSOCIATIVA_VPR]  WITH CHECK ADD  CONSTRAINT [FK_SEMEAR_ASSOCIATIVA_HPR_SEMEAR_RESERVA] FOREIGN KEY([SQ_RESERVA_FK])
REFERENCES [dbo].[SEMEAR_RESERVA] ([SQ_RESERVA])
GO

ALTER TABLE [dbo].[SEMEAR_ASSOCIATIVA_VPR] CHECK CONSTRAINT [FK_SEMEAR_ASSOCIATIVA_HPR_SEMEAR_RESERVA]
GO

ALTER TABLE [dbo].[SEMEAR_ASSOCIATIVA_VPR]  WITH CHECK ADD  CONSTRAINT [FK_SEMEAR_ASSOCIATIVA_HPR_SEMEAR_VIAGEM] FOREIGN KEY([SQ_VIAGEM_FK])
REFERENCES [dbo].[SEMEAR_VIAGEM] ([SQ_VIAGEM])
GO

ALTER TABLE [dbo].[SEMEAR_ASSOCIATIVA_VPR] CHECK CONSTRAINT [FK_SEMEAR_ASSOCIATIVA_HPR_SEMEAR_VIAGEM]
GO

