USE [tailandia]
GO

/****** Object:  Table [dbo].[SEMEAR_ASSOCIATIVA_T_VPR]    Script Date: 25/07/2023 21:01:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SEMEAR_ASSOCIATIVA_T_VPR](
	[SQ_TVPR_PK] [bigint] NOT NULL,
	[SQ_AVPR_FK] [bigint] NULL,
	[SQ_TRANSORTE_FK] [bigint] NULL,
	[DT_INCLUSAO] [datetime] NULL,
	[DT_EXCLUSAO] [datetime] NULL,
	[DT_EDICAO] [datetime] NULL,
 CONSTRAINT [PK_SEMEAR_ASSOCIATIVA_T_HPR] PRIMARY KEY CLUSTERED 
(
	[SQ_TVPR_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SEMEAR_ASSOCIATIVA_T_VPR]  WITH CHECK ADD  CONSTRAINT [FK_SEMEAR_ASSOCIATIVA_T_HPR_SEMEAR_ASSOCIATIVA_HPR] FOREIGN KEY([SQ_AVPR_FK])
REFERENCES [dbo].[SEMEAR_ASSOCIATIVA_VPR] ([SQ_HPR_PK])
GO

ALTER TABLE [dbo].[SEMEAR_ASSOCIATIVA_T_VPR] CHECK CONSTRAINT [FK_SEMEAR_ASSOCIATIVA_T_HPR_SEMEAR_ASSOCIATIVA_HPR]
GO

ALTER TABLE [dbo].[SEMEAR_ASSOCIATIVA_T_VPR]  WITH CHECK ADD  CONSTRAINT [FK_SEMEAR_ASSOCIATIVA_T_HPR_SEMEAR_TRANSPORTE] FOREIGN KEY([SQ_TRANSORTE_FK])
REFERENCES [dbo].[SEMEAR_TRANSPORTE] ([SQ_TRANSPORTE])
GO

ALTER TABLE [dbo].[SEMEAR_ASSOCIATIVA_T_VPR] CHECK CONSTRAINT [FK_SEMEAR_ASSOCIATIVA_T_HPR_SEMEAR_TRANSPORTE]
GO

