USE [tailandia]
GO

/****** Object:  Table [dbo].[SEMEAR_HP_IMAGEM]    Script Date: 25/07/2023 21:30:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SEMEAR_HP_IMAGEM](
	[SQ_IMAGEM_H] [bigint] NOT NULL,
	[SQ_HOSPEDAGEM_FK] [bigint] NULL,
	[IMAGEM] [image] NULL,
 CONSTRAINT [PK_SEMEAR_HP_IMAGEM] PRIMARY KEY CLUSTERED 
(
	[SQ_IMAGEM_H] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SEMEAR_HP_IMAGEM]  WITH CHECK ADD  CONSTRAINT [FK_SEMEAR_HP_IMAGEM_SEMEAR_HOSPEDAGEM] FOREIGN KEY([SQ_HOSPEDAGEM_FK])
REFERENCES [dbo].[SEMEAR_HOSPEDAGEM] ([SEQ_HOSPEDAGEM])
GO

ALTER TABLE [dbo].[SEMEAR_HP_IMAGEM] CHECK CONSTRAINT [FK_SEMEAR_HP_IMAGEM_SEMEAR_HOSPEDAGEM]
GO

